### ISSUE TITLE
spell module

### ISSUE THREAD

**Issue by gfurbush** [marklogic/RunDMC#560] opened 2016-04-11 23:44 UTC
In docapp, I noticed that the summary page for the spell modules contains both the javascript and XQuery output:

http://pubs.marklogic.com:8011/9.0/js/spell

  <span class="xquery">
  <p>To use the <code>spell.xqy</code> module in your own XQuery modules, 
  include the following line in your XQuery prolog:</p>
  <p><code>import module namespace spell = "http://marklogic.com/xdmp/spell" 
                                  at "/MarkLogic/spell.xqy";
     </code></p>
  <p>The library uses the <code>spell:</code> namespace, predefined in 
     the server.  </p>
  <p>The spelling correction functions (<code>spell:is-correct</code> and 
  <code>spell:suggest</code>) are built-in functions and do not require the 
  <code>import module</code> statement in the XQuery prolog.
  </p>
  </span>

  <span class="javascript">
  <p>To use the <code>spell</code> module in your own Server-Side JavaScript 
  modules, include the following line in your JavaScript program:</p>
  <p><code>var spell = require("/MarkLogic/spell"); </code></p>
  <p>The spelling correction functions (<code>spell.isCorrect</code> and 
  <code>spell.suggest</code>) are built-in functions and do not require the 
  <code>require</code> statement in your JavaScript code.
  </p>
  </span>
  <p>There are also Spell Built-In functions, which you use to check if
                  words are spelled correctly according to the dictionaries and to
                  suggest alternate spellings.
  </p>
  </apidoc:summary>

**Comment by dsokolsky** [comment] 2016-04-11 23:52
None of the list pages are paying attention to the class attributes, so they are showing both xquery and javascript content.  This is a problem in the setup.

**Comment by dsokolsky** [comment] 2016-04-12 01:14
Actually, upon further examination, I don't see this problem.  It seems like it is displaying it correctly, showing the xquery stuff for the xquery list and the js stuff for the javascript list.  @gfurbush, do you still see this?

**Comment by kcoleman-marklogic** [comment] 2016-04-12 14:21
FWIW, they look OK to me today. I looked at both XQuery & SJS landing pages for 8 and 9.

**Comment by dsokolsky** [comment] 2016-04-12 20:22
We all agree this is not a bug, so closing this.

**Closed by dsokolsky** 2016-04-12 20:22 UTC
